# Generated by Django 2.1.2 on 2018-10-23 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messengers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='from_user',
            new_name='owner_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='to_user',
            new_name='room_id',
        ),
    ]
